### PR TITLE
Justin krs/product channels GET

### PR DESCRIPTION
**Pull request by justinengle-krs**
Implementation:
image

Zeplin:
image

TODO: Edit /Delete

### CODE REVIEW

**Review by casperlotter — DISMISSED** [review]

**Comment by mannyqi** [comment]
@justinengle-krs when viewing the channels tab I see the following with no dev console errors
image

If I refresh this page, then I see this in the dev console:
image


If I then move the focus from this page (like click on my 2nd screen) and then click back on this channels page, I then get an additional error in my dev console:
image

**Comment by justinengle-krs** [comment]
> 

@mannyqi I think I resolved the issue where its stuck in a loading state, but for the other error I am struggling to reproduce. I am not sure if its the data in that scenario that I'm maybe not catering for.

Based on the error it looks like the variant channel is null. 

Is there a way for you to share the network responses for that product?

**Comment by matthampton-stock2shop** [comment]
@justinengle-krs This one has merge conflicts now - sorry!

**Comment by matthampton-stock2shop** [comment]
@mannyqi Is there anything left to do on this from a review perspective?

**Comment by mannyqi** [comment]
@justinengle-krs if you could please resolve conflicts. will review after

**Comment by mannyqi** [comment]
@justinengle-krs I'm still getting [this error](https://github.com/stock2shop/console_v2/pull/155#issuecomment-1600363750). 
I did figure out how to reproduce it though:

1. Create a new channel (e.g. WooCommerce) in the admin system
2. Login to the client and activate the newly created channel
Screenshot 2023-08-08 at 11 22 37
3. View any product's channel tab

---

When loading the product view's channel tab, the `GET variants/5313457/channels?token=XXXXXXXX` endpoint will return a response like this one:
```json
{
    "system_variant_channels": [
        {
            "id": 8973631,
            "created": "2023-02-24 13:56:16.000000",
            "channel_variant_code": "5313457",
            "variant_id": 5313457,
            "modified": "2023-05-17 09:48:13.000000",
            "channel_id": 47,
            "active": 1,
            "client_id": "21"
        },
        {
            "id": 8973633,
            "created": "2023-02-24 13:56:17.000000",
            "channel_variant_code": "5313457",
            "variant_id": 5313457,
            "modified": "2023-02-27 12:09:18.000000",
            "channel_id": 1881,
            "active": 1,
            "client_id": "21"
        },
        {
            "id": 10387918,
            "created": "2023-05-17 09:48:01.000000",
            "channel_variant_code": "39851748163642",
            "variant_id": 5313457,
            "modified": "2023-05-17 09:48:15.000000",
            "channel_id": 197,
            "active": 1,
            "client_id": "21"
        }
    ]
}
```

**Comment by justinengle-krs** [comment]
> @justinengle-krs I'm still getting [this error](https://github.com/stock2shop/console_v2/pull/155#issuecomment-1600363750). I did figure out how to reproduce it though:
> 
> 1. Create a new channel (e.g. WooCommerce) in the admin system
> 2. Login to the client and activate the newly created channel
> 
> Screenshot 2023-08-08 at 11 22 37 3. View any product's channel tab
> When loading the product view's channel tab, the `GET variants/5313457/channels?token=XXXXXXXX` endpoint will return a response like this one:
> 
> ```json
> {
>     "system_variant_channels": [
>         {
>             "id": 8973631,
>             "created": "2023-02-24 13:56:16.000000",
>             "channel_variant_code": "5313457",
>             "variant_id": 5313457,
>             "modified": "2023-05-17 09:48:13.000000",
>             "channel_id": 47,
>             "active": 1,
>             "client_id": "21"
>         },
>         {
>             "id": 8973633,
>             "created": "2023-02-24 13:56:17.000000",
>             "channel_variant_code": "5313457",
>             "variant_id": 5313457,
>             "modified": "2023-02-27 12:09:18.000000",
>             "channel_id": 1881,
>             "active": 1,
>             "client_id": "21"
>         },
>         {
>             "id": 10387918,
>             "created": "2023-05-17 09:48:01.000000",
>             "channel_variant_code": "39851748163642",
>             "variant_id": 5313457,
>             "modified": "2023-05-17 09:48:15.000000",
>             "channel_id": 197,
>             "active": 1,
>             "client_id": "21"
>         }
>     ]
> }
> ```

@mannyqi I don't think have any admin login to be able to added a channel. Not to sure why adding one would cause an issue though. I am struggling to reproduce this with my current channels

**Comment by mannyqi** [comment]
@justinengle-krs I'll try and have a closer look at this a little later to see if I can figure out why it's happening.

**Comment by matthampton-stock2shop** [comment]
@mannyqi I think I'm going to merge this - just to get things moving... Would you mind creating an issue from the last bug that you ran in to so we can fix it in a follow-up?

**Comment by mannyqi** [comment]
> Would you mind creating an issue from the last bug that you ran in to so we can fix it in a follow-up?

Done. https://github.com/stock2shop/console_v2/issues/207

**Pull request merged**
